#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey -v
bindkey "^R" history-incremental-pattern-search-backward
bindkey "^L" autosuggest-accept

eval "$(starship init zsh)"

export STARSHIP_CONFIG="$HOME/.zprezto/starship.toml" 
export VISUAL=vim
export EDITOR=vim
export PATH=.:/Users/ericpridham/bin:~/.composer/vendor/bin:$PATH
